######################################################################
# Automatically generated by qmake (2.01a) Mon May 17 20:50:58 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ../../src/
MOC_DIR = moc
OBJECTS_DIR = obj

# Input
HEADERS += canvas.h

SOURCES += canvas.cpp
SOURCES += main.cpp

QT += xml
